# Numpy Library in Python part 1

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)
print(type(arr))


[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [4]:
# use a tuple to crearte a anumpy array
arr = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
# Dimentions of an array
arr = np.array(20)
print(arr.ndim)
print(arr)

0
20


In [6]:
# 1d array
arr = np.array([1, 2, 3, 4, 5])
arr.ndim

1

In [7]:
# 2d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [8]:
arr = np.array([1.1,2.2])
print(arr)

[1.1 2.2]


In [9]:
# 3d array
arr =([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr)


[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [10]:
arr = np.array([1,2,3,4],ndmin=6)
print(arr)

[[[[[[1 2 3 4]]]]]]


In [11]:
# indeing in numpy array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[2])
print([6])
print([8])


3
[6]
[8]
