# Day-13 Numpy Part 2 Advanced Numpy

## Slicing in numpy array

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:6:2])

[2 4 6]


In [4]:
# slicing in 2d array
a = np.array([[10,20,30,40,50,],[60,70,80,90,100]])
print(a[0,1:4])

[20 30 40]


In [5]:
# checking the data type of an array
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [6]:
arr = np.array(['animals','bat','cat'])
print(arr.dtype)

<U7


In [7]:
# Creatng arrays with a defined data type
arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [8]:
# create an array with 4bytes integer
arr = np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [9]:
# Numpy Array Shape
## The shape of an array is the numer in each dimension

# print the shape of an array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)


(2, 4)


In [10]:
arr = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(arr.shape)


(1, 3, 4)


In [11]:
# Joining numpy array
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a = np.concatenate((a1,a2))
print(a)

[1 2 3 4 5 6]


In [12]:
# Joining 2d array
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
a = np.concatenate((a1,a2),axis=1)
print(a)

[[1 2 5 6]
 [3 4 7 8]]


In [13]:
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
a = np.concatenate((a1,a2),axis=0)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [14]:
# Spliting numpy array --- 3 parts
arr = np.array([1,2,3,4,5,6])
narr = np.array_split(arr,4)
print(narr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [16]:
# Ravel and Flatten Function ---: Convert multidimenstional array to 1D array.

m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('The dimention is ',m.ndim)
n = m.ravel()
print('\n')
print('The new dimension is ', n.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
The dimention is  3


The new dimension is  1


In [17]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print('The dimention is ',m.ndim)
n = m.flatten()
print('\n')
print('The new dimension is ', n.ndim)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
The dimention is  3


The new dimension is  1


In [19]:
c = np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]])
print(c)
print(c.ndim)
d = c.ravel()
print(d)
print(d.ndim)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
4
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [22]:
# Unique Function

k = np.array([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10])
print(k)
x = np.unique(k, return_index=True,  return_counts=True)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]


In [23]:
# Delete Function

a = np.array([  1,2,3])
print(a)
np.delete(a,[1])

[1 2 3]


array([1, 3])

In [25]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

y = np.delete(x, 1, axis=0) # delete the second row
print(y)

[[ 1  2  3  4]
 [ 9 10 11 12]]
